services:
  betterthanmicrospos:
    image: ${DOCKER_REGISTRY-}betterthanmicrospos
    build:
      context: .
      dockerfile: BetterThanMicrosPOS/Dockerfile
    ports:    
      - "5000:8080"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ConnectionStrings__DefaultConnection=server=mariadb;port=3306;database=mysql ;user=root;password=123456;
    networks:
      - appnet
networks:
  appnet:
    external: true
    name: appnet
